### ISSUE TITLE
Pretrained model innaccesible

### ISSUE THREAD

**Issue by mariembenslama** [Holmeyoung/crnn_pytorch#4]
Hello,

I hope you're doing good,

Is it okay if you put your pretained model "crnn.pth" on google drive?

Because pan.baidu demands a chinese phone which is inaccessible in some countries.
^_^
Thank you.

**Comment by Holmeyoung** [comment]
Hi, sorry to reply now, i am on vacation. The pretrained model is just a demo and my training picture looks very nice. So my pretrained model is just used to tell you that my repository is useful for those having encoding problems. But i think you are right, i will add a English pretrained model to it.

**Comment by mariembenslama** [comment]
I see, and thank you very much. 😊

**Comment by xiechun0318** [comment]
Hi,
May I know where you downloaded the pretrained model eventually?
I cannot find any link to download it other than pan.baidu, and yes it is still not available for non-Chinese users.
Thanks.

**Comment by mineshmathew** [comment]
to download from Baidu,
see the answer by ShinyMarusu
https://www.reddit.com/r/Piracy/comments/auhyxk/how_do_i_download_from_panbaidu/

**Comment by mineshmathew** [comment]
Here is a copy of the model in Baidu disk, in google drive
https://drive.google.com/drive/folders/1FhXvPtitX6tWYocFZiZBRzVHjK2o640u?usp=sharing
