### ISSUE TITLE
Training the model using Arabic characters

### ISSUE THREAD

**Issue by niddal-imam** [Holmeyoung/crnn_pytorch#6]
Hi Holmeyoung,

I have built my own dataset, which consist of Arabic characters. I have followed your steps for building my dataset. I was able to convert my dataset to lmdb successfully. However, when I tried to train the model,  got this error:
CRNN(
  (cnn): Sequential(
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU(inplace)
    (pooling0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU(inplace)
    (pooling1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu2): ReLU(inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU(inplace)
    (pooling2): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=1, ceil_mode=False)
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu4): ReLU(inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU(inplace)
    (pooling3): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=1, ceil_mode=False)
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu6): ReLU(inplace)
  )
  (rnn): Sequential(
    (0): BidirectionalLSTM(
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=256, bias=True)
    )
    (1): BidirectionalLSTM(
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=69, bias=True)
    )
  )
)
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 154, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/Volumes/EXTERNAL/Models/crnn_pytorch-master/utils.py", line 61, in encode
    index = self.dict[char]
KeyError: '٩'

It sounds like the model can't recognize Arabic characters. Any suggestions?

Thanks

**Comment by Holmeyoung** [comment]
Hi, you need to add the characters appearing in your training labels to the `alphabets.py` .
For example
```python
alphabet = '''٩'''
```

**Comment by niddal-imam** [comment]
Thank you for your quick replay. I just added the characters to the alphabets.py and it works. However, as I can't download your pre-trained model, I used different pre-trained models, but I got this error:

RuntimeError: Error(s) in loading state_dict for CRNN:
	size mismatch for rnn.1.embedding.bias: copying a param with shape torch.Size([37]) from checkpoint, the shape in current model is torch.Size([71]).
	size mismatch for rnn.1.embedding.weight: copying a param with shape torch.Size([37, 512]) from checkpoint, the shape in current model is torch.Size([71, 512]).
